### ISSUE TITLE
Invoking gomp produces Index Out of Range error

### ISSUE THREAD

**Issue by GLMeece** [MarkForged/GOMP#5] opened 2020-07-31 00:43 UTC
# Essential Issue

Attempting to compare two branches (main and a derivative), returns an "index out of range" error

## Steps to Reproduce

1. Execute `gomp dev master`
2. The following is returned on the terminal:

```bash
dev (src)                                                                        master (dest)
-------------------------------------------------------------------------------  -------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gmeece/.environments/[obfuscated]/bin/gomp", line 8, in <module>
    sys.exit(process_commands())
  File "/Users/gmeece/.environments/[obfuscated]/lib/python3.7/site-packages/gomp/gomp.py", line 364, in process_commands
    show_side_by_side()
  File "/Users/gmeece/.environments/[obfuscated]/lib/python3.7/site-packages/gomp/gomp.py", line 268, in show_side_by_side
    common_hash = find_first_common_hash(source_history, destination_history, 4)
  File "/Users/gmeece/.environments/[obfuscated]/lib/python3.7/site-packages/gomp/gomp.py", line 132, in find_first_common_hash
    if source_commit[i][0] == _hash:
IndexError: list index out of range
```

Examination of method based on line error (line has `if source_commit[i][0] == _hash:`):

```python
# Finds the first common hash between two histories
def find_first_common_hash(source_commit, destination_commit, previous=0):
    source_map = {}
    destination_map = {}
    _hash = '?'
    # Find first common hash occurence
    for i in range(min(len(source_commit), len(destination_commit))):
        source_hash = source_commit[i][0]
        destination_hash = destination_commit[i][0]
        source_map[source_hash] = i
        destination_map[destination_hash] = i
        if source_hash in destination_map:
            _hash = source_commit[i][0]
            break
        if destination_hash in source_map:
            _hash = destination_commit[i][0]
            break
    # Traverse either history to find that hash and select 'previous' hashes ago
    i = 0
    while True:
        if source_commit[i][0] == _hash:
            break
        i += 1
    # min here avoids out of bounds error in short repos
    i += min(previous, len(source_commit) - i - 1)
    return source_commit[i][0]
```

## Expected Behavior

I expected a return similar to what the README shows:

![Gomp Branch Screenshot](https://raw.githubusercontent.com/MarkForged/GOMP/main/docs/gomp_branch.png)

## Version and Platform

* Gomp = `1.0.2`
* Python = `3.7.7`
* macOS = `10.14.6` (Mojave)

**Comment by arikwex** [comment] 2020-07-31 07:33
Thanks for the detailed report!

I've got a couple questions:
1) Do either of the branches involved have zero commits?
2) Does the repository use a merge (not rebase) strategy primarily?

Since this workflow was primarily built around a rebase strategy, there may be issues that crop up with merge commits that we can work to resolve. I tested out gomp against a repo that had a merge-heavy history and found the following:
```
# This works
gomp head~696 head~3000

# This fails similar to the error you've provided
gomp head~695 head~3000
```

I started digging in to this and I found the primary culprit: https://github.com/MarkForged/GOMP/blob/9e95411b0446f95dda794f0f324a263fe56fe938/gomp.py#L136

In a rebase-only world, history before a matching commit hash is guaranteed to be identical. With that knowledge, the approach linked above works just fine. It translates to roughly: "Hey, I found the first commit hash that is identical between the two branches, so now I'm going to give you a few contextual commits that precede that." Annnnnd this is where the merge strategy comes in to cause issues with gomp.

See this sample history:
```
    8ceea82 feature A
    e9ea439 Merge of 'feature B'
    ca8ea84 First common commit hash     ca8ea84 First common commit hash
[?] 4dca980 feature B                    0cd9f50 feature C
    0cd9f50 feature C                    1ce60e2 feature D
```
The commit flagged with the "?" is what can cause issues here. Specifically, gomp will fail if there are 5 or more injected commits between the branch histories after the first common commit was found. whew - that was a journey.

I have a patch that seems promising and I'll try to get a PR up later today.

**Comment by arikwex** [comment] 2020-08-01 00:17
Ok I've put up a PR.
https://github.com/MarkForged/GOMP/pull/11/commits/96b332ec7f844cb09a98441dc2ce0a62ebb0820a
If you have a chance to try it out, I'd like to know if this resolves your issue.

**Comment by GLMeece** [comment] 2020-08-01 13:25
Regarding:

> Do either of the branches involved have zero commits?

Ha, yes the secondary branch is brand new. I was just kicking the tires on your tool

> Does the repository use a merge (not rebase) strategy primarily?

I've used rebase a lot previously, which is why I was interested in the tool. Since it's an almost new repo, I just wanted to get a feel for the tool.

**Summary**: I inadvertently created an edge case. Sorry, not sorry!

**Comment by arikwex** [comment] 2020-08-03 13:59
Pushing the limits of the tool is very welcome here, no need to be sorry! :D In my PR (now merged) I believe I've addressed the root cause of the `index out of ranger error` you were experiencing. We'll be putting together a new release shortly that will include this fix.

**Comment by philipkiely-markforged** [comment] 2020-08-03 15:20
The release is up, version 1.1 on PyPi and GitHub, which should resolve the issue. Thank you for reporting it!

**Closed as completed by philipkiely-markforged** 2020-08-03 15:20 UTC
Labels: bug
